tgrpc:
    host: 127.0.0.1
    port: 9001
    registery: consul
    ttl: 8000
    maxCapacity: 3
    requestTimeoutMillis: 8000
    maxTotal: 3
    maxIdle: 3
    minIdle: 0
    borrowMaxWaitMillis: 5000
