tgrpc:
    server:
        host: 127.0.0.1
        port: 9001
        serviceName: testService
        serviceId: dev
        registery: consul
        consulHost: 127.0.0.1
        consulPort: 8500
        ttl: 8000
        maxCapacity: 3
        requestTimeoutMillis: 8000
        maxTotal: 3
        maxIdle: 3
        minIdle: 1
        borrowMaxWaitMillis: 5000

    client:
        registery: consul
        consulHost: 127.0.0.1
        consulPort: 8500
        breaker: true
        maxCapacity: 3
        maxTotal: 3
        maxIdle: 3
        minIdle: 0
        borrowMaxWaitMillis: 5000
        clients:
            - serviceName: testService
              requestTimeoutMillis: 2000
              interfaces:
                    - com.tg.rpc.example.service.EchoService
                    - com.tg.rpc.example.service.TestService
              providerList: 127.0.0.1:8080
            - serviceName: testService
                            requestTimeoutMillis: 2000
                            interfaces:
                                  - com.tg.rpc.example.service.EchoService
                                  - com.tg.rpc.example.service.TestService
                            providerList: 127.0.0.1:8080


